language: node_js
node_js:
  - 7
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  repo: cectf/cectf.github.io
  on:
    branch: master
